##print("H\tello\nWo rld")
##print("Python can be used for printing")
##print("Each new print statement is printed on a new line!")
##print("We have extra characters that have special meaning too!")
##print("\tbackslash t prints out a tab\twhich is like several spaces")
##print("backslash n\nprints a new line\neach time you type it\n!")
##print("J\nA\nK\nS\nH")
##print('Sunday\nMonday\nTuesday\nWednesday\nThurday\nFriday\nSaturday')
##print("HOW MANY, HOW MUCH\t\tby Shel Silverstein\nHow many slams in an old screen door?\n\tDepends how loud you shut it.\n\n\nHow many slices in a bread?\n\tDepends how thin you cut it.\n\n\nHow much good inside a day?\n\tDepends how good you live 'em\n\n\nHow much love inside a friend?\n\tDepends how much you give 'em.")
##print("FALLING UP \t\t\t by Shel Silverstein\nI tripped on my shoelace\nAnd I fell up\nUp to the roof tops,\n\tUp over the town,\n\t\tUp past the tree tops,\n\t\t\tUp over the mountains,\n\t\t\t\tUp where the colours,\n\t\t\t\t\tBlend into the sounds.\n\t\t\t\tBut it got me so dizzy\n\t\tWhen I looked around,\n\tI got sick to my stomach\nAnd I threw down")
print("Sr\tName\tGrade\n1.\tJaksh\t4\n2.\tJiya\t4\n3.\tVivana\t8\n4.\tSamman\t6")
